/**
 * Code View Component
 *
 * Exports the workflow as executable code in TypeScript, Python, or JSON format.
 * Features syntax highlighting, copy to clipboard, and download functionality.
 */

import { useState, useMemo, useCallback } from "react";
import type { Node, Edge } from "reactflow";
import clsx from "clsx";

// ── Types ──

interface CodeViewProps {
  nodes: Node[];
  edges: Edge[];
  workflowName: string;
  workflowId?: string;
}

type CodeLanguage = "typescript" | "python" | "json";

// ── Code Generation ──

function generateWorkflowJSON(
  nodes: Node[],
  edges: Edge[],
  workflowName: string,
  workflowId: string
): string {
  const graphData = {
    id: workflowId,
    name: workflowName,
    nodes: nodes.map((n) => ({
      id: n.id,
      type: n.type,
      label: n.data.label,
      config: n.data.config || {},
      position: n.position,
    })),
    edges: edges.map((e) => ({
      id: e.id,
      source: e.source,
      target: e.target,
      sourceHandle: e.sourceHandle,
      targetHandle: e.targetHandle,
      label: e.label,
    })),
  };
  return JSON.stringify(graphData, null, 2);
}

function generateTypeScriptCode(
  nodes: Node[],
  edges: Edge[],
  workflowName: string,
  workflowId: string
): string {
  const nodesCode = nodes
    .map((n) => {
      const config = JSON.stringify(n.data.config || {}, null, 6).replace(
        /\n/g,
        "\n      "
      );
      return `    {
      id: '${n.id}',
      type: '${n.type}',
      label: '${n.data.label || n.type}',
      config: ${config},
    }`;
    })
    .join(",\n");

  const edgesCode = edges
    .map((e) => {
      const parts = [`id: '${e.id}'`, `source: '${e.source}'`, `target: '${e.target}'`];
      if (e.sourceHandle) parts.push(`sourceHandle: '${e.sourceHandle}'`);
      if (e.targetHandle) parts.push(`targetHandle: '${e.targetHandle}'`);
      if (e.label) parts.push(`label: '${e.label}'`);
      return `    { ${parts.join(", ")} }`;
    })
    .join(",\n");

  return `/**
 * ${workflowName}
 *
 * Generated by Nebula Agent Builder
 * @generated
 */

import {
  WorkflowExecutor,
  WorkflowDefinition,
  MockLLMProvider,
  OpenAIProvider,
} from '@nebula/workflow-engine';

// Workflow Definition
const workflow: WorkflowDefinition = {
  id: '${workflowId}',
  name: '${workflowName}',
  nodes: [
${nodesCode}
  ],
  edges: [
${edgesCode}
  ],
};

// Initialize the executor with your LLM provider
// Option 1: Use OpenAI
// const llmProvider = new OpenAIProvider({ apiKey: process.env.OPENAI_API_KEY });

// Option 2: Use Mock provider for testing
const llmProvider = new MockLLMProvider();

const executor = new WorkflowExecutor(workflow, {
  llmProvider,
  maxExecutionTime: 300000, // 5 minutes
  maxNodeExecutions: 1000,
  onNodeStart: (node, context) => {
    console.log(\`Starting node: \${node.id}\`);
  },
  onNodeComplete: (node, result) => {
    console.log(\`Completed node: \${node.id} - Status: \${result.status}\`);
  },
});

// Run the workflow
async function runWorkflow(input: Record<string, unknown> = {}) {
  console.log('Starting workflow execution...');

  const result = await executor.run(input);

  if (result.success) {
    console.log('Workflow completed successfully!');
    console.log('Outputs:', result.outputs);
  } else {
    console.error('Workflow failed:', result.error?.message);
  }

  console.log(\`Execution time: \${result.executionTime}ms\`);

  return result;
}

// Export for use in your application
export { workflow, executor, runWorkflow };

// Example usage:
// runWorkflow({ userInput: 'Hello, world!' });
`;
}

function generatePythonCode(
  nodes: Node[],
  edges: Edge[],
  workflowName: string,
  workflowId: string
): string {
  const nodesCode = nodes
    .map((n) => {
      const config = JSON.stringify(n.data.config || {}, null, 8)
        .replace(/"/g, "'")
        .replace(/\n/g, "\n        ");
      return `        {
            'id': '${n.id}',
            'type': '${n.type}',
            'label': '${n.data.label || n.type}',
            'config': ${config},
        }`;
    })
    .join(",\n");

  const edgesCode = edges
    .map((e) => {
      const parts = [`'id': '${e.id}'`, `'source': '${e.source}'`, `'target': '${e.target}'`];
      if (e.sourceHandle) parts.push(`'sourceHandle': '${e.sourceHandle}'`);
      if (e.targetHandle) parts.push(`'targetHandle': '${e.targetHandle}'`);
      if (e.label) parts.push(`'label': '${e.label}'`);
      return `        { ${parts.join(", ")} }`;
    })
    .join(",\n");

  return `"""
${workflowName}

Generated by Nebula Agent Builder
"""

import asyncio
from typing import Any, Dict, Optional
from dataclasses import dataclass
from nebula_workflow_engine import (
    WorkflowExecutor,
    WorkflowDefinition,
    MockLLMProvider,
    OpenAIProvider,
)

# Workflow Definition
workflow: WorkflowDefinition = {
    'id': '${workflowId}',
    'name': '${workflowName}',
    'nodes': [
${nodesCode}
    ],
    'edges': [
${edgesCode}
    ],
}


def create_executor(use_mock: bool = True) -> WorkflowExecutor:
    """Create a workflow executor with the configured LLM provider."""

    if use_mock:
        # Use mock provider for testing
        llm_provider = MockLLMProvider()
    else:
        # Use OpenAI provider
        import os
        llm_provider = OpenAIProvider(api_key=os.environ.get('OPENAI_API_KEY'))

    executor = WorkflowExecutor(
        workflow=workflow,
        llm_provider=llm_provider,
        max_execution_time=300000,  # 5 minutes
        max_node_executions=1000,
        on_node_start=lambda node, ctx: print(f"Starting node: {node['id']}"),
        on_node_complete=lambda node, result: print(
            f"Completed node: {node['id']} - Status: {result['status']}"
        ),
    )

    return executor


async def run_workflow(
    input_data: Optional[Dict[str, Any]] = None,
    use_mock: bool = True
) -> Dict[str, Any]:
    """Execute the workflow with the given input."""

    input_data = input_data or {}
    executor = create_executor(use_mock=use_mock)

    print('Starting workflow execution...')

    result = await executor.run(input_data)

    if result['success']:
        print('Workflow completed successfully!')
        print('Outputs:', result['outputs'])
    else:
        print('Workflow failed:', result.get('error', {}).get('message'))

    print(f"Execution time: {result['execution_time']}ms")

    return result


# Entry point
if __name__ == '__main__':
    # Example usage
    result = asyncio.run(run_workflow(
        input_data={'user_input': 'Hello, world!'},
        use_mock=True,
    ))
`;
}

// ── Syntax Highlighting ──

function highlightJSON(code: string): JSX.Element[] {
  const lines = code.split("\n");
  return lines.map((line, i) => {
    // Simple JSON syntax highlighting
    let highlighted = line
      // Property keys
      .replace(/"([^"]+)":/g, '<span class="text-blue-600">"$1"</span>:')
      // String values
      .replace(/: "([^"]*)"/g, ': <span class="text-green-600">"$1"</span>')
      // Numbers
      .replace(/: (\d+\.?\d*)/g, ': <span class="text-amber-600">$1</span>')
      // Booleans and null
      .replace(/: (true|false|null)/g, ': <span class="text-purple-600">$1</span>');

    return (
      <div key={i} className="flex">
        <span className="select-none text-gray-400 w-10 text-right pr-4">
          {i + 1}
        </span>
        <span dangerouslySetInnerHTML={{ __html: highlighted }} />
      </div>
    );
  });
}

function highlightTypeScript(code: string): JSX.Element[] {
  const lines = code.split("\n");
  return lines.map((line, i) => {
    let highlighted = line
      // Comments
      .replace(/(\/\/.*$)/g, '<span class="text-gray-500">$1</span>')
      .replace(/(\/\*\*?|\*\/|\*)/g, '<span class="text-gray-500">$1</span>')
      // Keywords
      .replace(
        /\b(import|export|from|const|let|var|function|async|await|return|if|else|new|class|type|interface)\b/g,
        '<span class="text-purple-600 font-medium">$1</span>'
      )
      // Types
      .replace(
        /\b(WorkflowExecutor|WorkflowDefinition|MockLLMProvider|OpenAIProvider|Record|string|number|boolean|unknown)\b/g,
        '<span class="text-blue-600">$1</span>'
      )
      // Strings
      .replace(/'([^']*)'/g, '<span class="text-green-600">\'$1\'</span>')
      .replace(/`([^`]*)`/g, '<span class="text-green-600">`$1`</span>')
      // Template literals with expressions
      .replace(/\$\{([^}]+)\}/g, '<span class="text-amber-600">${$1}</span>')
      // Numbers
      .replace(/\b(\d+)\b/g, '<span class="text-amber-600">$1</span>')
      // Console
      .replace(/console\.(log|error|warn)/g, '<span class="text-cyan-600">console.$1</span>');

    return (
      <div key={i} className="flex">
        <span className="select-none text-gray-400 w-10 text-right pr-4">
          {i + 1}
        </span>
        <span dangerouslySetInnerHTML={{ __html: highlighted }} />
      </div>
    );
  });
}

function highlightPython(code: string): JSX.Element[] {
  const lines = code.split("\n");
  return lines.map((line, i) => {
    let highlighted = line
      // Comments
      .replace(/(#.*$)/g, '<span class="text-gray-500">$1</span>')
      // Docstrings (simple case)
      .replace(/^(\s*)(""".*""")$/g, '$1<span class="text-gray-500">$2</span>')
      .replace(/^(\s*)(""")/g, '$1<span class="text-gray-500">$2</span>')
      // Keywords
      .replace(
        /\b(import|from|def|async|await|return|if|else|elif|class|None|True|False|lambda|or|and|not|in|is|with|as|try|except|finally|raise|pass|for|while|break|continue)\b/g,
        '<span class="text-purple-600 font-medium">$1</span>'
      )
      // Decorators
      .replace(/@(\w+)/g, '<span class="text-amber-600">@$1</span>')
      // Types
      .replace(
        /\b(Dict|List|Optional|Any|str|int|float|bool|WorkflowExecutor|WorkflowDefinition|MockLLMProvider|OpenAIProvider)\b/g,
        '<span class="text-blue-600">$1</span>'
      )
      // Strings
      .replace(/'([^']*)'/g, '<span class="text-green-600">\'$1\'</span>')
      // f-strings
      .replace(/f"([^"]*)"/g, '<span class="text-green-600">f"$1"</span>')
      // Numbers
      .replace(/\b(\d+)\b/g, '<span class="text-amber-600">$1</span>')
      // Print
      .replace(/\bprint\b/g, '<span class="text-cyan-600">print</span>');

    return (
      <div key={i} className="flex">
        <span className="select-none text-gray-400 w-10 text-right pr-4">
          {i + 1}
        </span>
        <span dangerouslySetInnerHTML={{ __html: highlighted }} />
      </div>
    );
  });
}

// ── Component ──

export function CodeView({
  nodes,
  edges,
  workflowName,
  workflowId = crypto.randomUUID(),
}: CodeViewProps) {
  const [language, setLanguage] = useState<CodeLanguage>("typescript");
  const [copied, setCopied] = useState(false);

  // Generate code based on selected language
  const code = useMemo(() => {
    switch (language) {
      case "typescript":
        return generateTypeScriptCode(nodes, edges, workflowName, workflowId);
      case "python":
        return generatePythonCode(nodes, edges, workflowName, workflowId);
      case "json":
        return generateWorkflowJSON(nodes, edges, workflowName, workflowId);
      default:
        return "";
    }
  }, [nodes, edges, workflowName, workflowId, language]);

  // Syntax highlighted code
  const highlightedCode = useMemo(() => {
    switch (language) {
      case "typescript":
        return highlightTypeScript(code);
      case "python":
        return highlightPython(code);
      case "json":
        return highlightJSON(code);
      default:
        return code.split("\n").map((line, i) => (
          <div key={i} className="flex">
            <span className="select-none text-gray-400 w-10 text-right pr-4">
              {i + 1}
            </span>
            <span>{line}</span>
          </div>
        ));
    }
  }, [code, language]);

  // Copy to clipboard
  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [code]);

  // Download file
  const handleDownload = useCallback(() => {
    const extensions: Record<CodeLanguage, string> = {
      typescript: "ts",
      python: "py",
      json: "json",
    };

    const mimeTypes: Record<CodeLanguage, string> = {
      typescript: "text/typescript",
      python: "text/x-python",
      json: "application/json",
    };

    const fileName = `${workflowName.replace(/\s+/g, "-").toLowerCase()}.${extensions[language]}`;
    const blob = new Blob([code], { type: mimeTypes[language] });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = fileName;
    a.click();
    URL.revokeObjectURL(url);
  }, [code, language, workflowName]);

  return (
    <div className="flex-1 flex flex-col bg-surface-1">
      {/* Header with language tabs and actions */}
      <div className="flex items-center justify-between px-4 py-2 border-b border-surface-3 bg-white">
        {/* Language tabs */}
        <div className="flex items-center gap-1 bg-surface-1 rounded-lg p-0.5">
          {(["typescript", "python", "json"] as const).map((lang) => (
            <button
              key={lang}
              onClick={() => setLanguage(lang)}
              className={clsx(
                "px-3 py-1.5 text-xs font-medium rounded-md transition-colors",
                language === lang
                  ? "bg-white text-gray-800 shadow-sm"
                  : "text-surface-dark-4 hover:text-gray-700"
              )}
            >
              {lang === "typescript" && "TypeScript"}
              {lang === "python" && "Python"}
              {lang === "json" && "JSON"}
            </button>
          ))}
        </div>

        {/* Actions */}
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className={clsx(
              "nebula-btn-secondary text-xs flex items-center gap-1.5",
              copied && "bg-green-50 text-green-700 border-green-200"
            )}
          >
            {copied ? (
              <>
                <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
                Copied!
              </>
            ) : (
              <>
                <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                  />
                </svg>
                Copy
              </>
            )}
          </button>

          <button
            onClick={handleDownload}
            className="nebula-btn-secondary text-xs flex items-center gap-1.5"
          >
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"
              />
            </svg>
            Download
          </button>
        </div>
      </div>

      {/* Code display */}
      <div className="flex-1 overflow-auto p-4">
        <div className="bg-white border border-surface-3 rounded-lg overflow-hidden">
          {/* File info header */}
          <div className="flex items-center gap-2 px-4 py-2 bg-surface-1 border-b border-surface-3">
            <div className="flex gap-1.5">
              <span className="w-3 h-3 rounded-full bg-red-400" />
              <span className="w-3 h-3 rounded-full bg-yellow-400" />
              <span className="w-3 h-3 rounded-full bg-green-400" />
            </div>
            <span className="text-xs text-surface-dark-4 font-mono ml-2">
              {workflowName.replace(/\s+/g, "-").toLowerCase()}
              {language === "typescript" && ".ts"}
              {language === "python" && ".py"}
              {language === "json" && ".json"}
            </span>
          </div>

          {/* Code content */}
          <pre className="p-4 text-xs font-mono text-gray-700 overflow-x-auto leading-relaxed">
            {highlightedCode}
          </pre>
        </div>
      </div>

      {/* Footer info */}
      <div className="px-4 py-2 border-t border-surface-3 bg-white">
        <div className="flex items-center justify-between text-xs text-surface-dark-4">
          <span>
            {nodes.length} nodes, {edges.length} edges
          </span>
          <span>
            {language === "typescript" && "Uses @nebula/workflow-engine"}
            {language === "python" && "Uses nebula_workflow_engine"}
            {language === "json" && "Raw workflow definition"}
          </span>
        </div>
      </div>
    </div>
  );
}

export default CodeView;
