/**
 * Workstream types — a workstream represents a unit of work
 * (feature request, bug fix, new service, etc.)
 */

export interface Workstream {
  id: string;
  projectId: string;
  title: string;
  description: string;
  status: WorkstreamStatus;
  createdAt: string;
  updatedAt: string;
  completedAt?: string;

  /** The user request that initiated this workstream */
  userRequest: string;

  /** Attached inputs */
  attachments: Attachment[];

  /** The plan generated by CTO Agent */
  plan?: WorkstreamPlan;

  /** Current phase of execution */
  currentPhase: WorkPhase;

  /** Associated run IDs */
  runIds: string[];

  /** Linear references */
  linearEpicId?: string;
  linearIssueIds: string[];

  /** Figma references */
  figmaFileIds: string[];

  /** Repository branches created for this workstream */
  branches: WorkstreamBranch[];

  /** Evidence collected during execution */
  evidence: Evidence[];
}

export type WorkstreamStatus =
  | "draft"
  | "planning"
  | "in-progress"
  | "testing"
  | "deploying"
  | "completed"
  | "failed"
  | "paused";

export type WorkPhase =
  | "design"
  | "build"
  | "test"
  | "deploy"
  | "document"
  | "completed";

export interface Attachment {
  id: string;
  name: string;
  type: AttachmentType;
  path: string;
  size: number;
  mimeType: string;
  uploadedAt: string;
}

export type AttachmentType = "prd" | "design" | "image" | "pdf" | "document" | "other";

export interface WorkstreamPlan {
  id: string;
  phases: PlanPhase[];
  decisions: PlanDecision[];
  createdAt: string;
  updatedAt: string;
}

export interface PlanPhase {
  id: string;
  name: string;
  description: string;
  status: "pending" | "in-progress" | "completed" | "skipped";
  tasks: PlanTask[];
}

export interface PlanTask {
  id: string;
  title: string;
  description: string;
  status: "pending" | "in-progress" | "completed" | "failed" | "skipped";
  assignedAgent?: string;
  evidence?: Evidence[];
}

export interface PlanDecision {
  id: string;
  question: string;
  context: string;
  impact: string;
  recommendation: string;
  alternatives: DecisionAlternative[];
  status: "pending" | "resolved";
  resolution?: string;
  resolvedBy?: string;
  resolvedAt?: string;
}

export interface DecisionAlternative {
  option: string;
  tradeoffs: string;
}

export interface WorkstreamBranch {
  repositoryId: string;
  branchName: string;
  status: "active" | "merged" | "closed";
  commits: number;
}

export interface Evidence {
  id: string;
  type: EvidenceType;
  title: string;
  description: string;
  timestamp: string;
  data: Record<string, unknown>;
  links: EvidenceLink[];
}

export type EvidenceType =
  | "code-change"
  | "test-result"
  | "deployment"
  | "documentation"
  | "linear-ticket"
  | "design-reference"
  | "security-scan"
  | "performance-report";

export interface EvidenceLink {
  label: string;
  url: string;
  type: "repository" | "deployment" | "obsidian" | "linear" | "figma" | "external";
}

/**
 * Conversation types for the chat interface
 */
export interface Conversation {
  id: string;
  workstreamId: string;
  messages: ConversationMessage[];
  createdAt: string;
}

export interface ConversationMessage {
  id: string;
  role: "user" | "assistant" | "system";
  content: string;
  timestamp: string;
  attachments?: Attachment[];
  mentions?: Mention[];
  agentId?: string;
  agentName?: string;
}

export interface Mention {
  type: "agent" | "file" | "ticket" | "service";
  id: string;
  label: string;
}
